@startuml

title 图解 Java Collection Framwork

left to right direction

' java.util
' tool class

class Object
class Arrays
class Collections

Object <|-- Arrays
Object <|-- Collections

' interface hierarchy tree

interface Collection
interface Set
    interface SortedSet
        interface NavigableSet
interface List
interface Queue
    interface Deque
interface Map
    interface SortedMap
        interface NavigableMap

Collection <|-- Queue
Queue <|-- Deque

Collection <|-- Set
Set <|-- SortedSet
SortedSet <|-- NavigableSet

Collection <|-- List

Map <|-- SortedMap
SortedMap <|-- NavigableMap

' impl class

class LinkedList
class ArrayList
class Vector
    class Stack
class PriorityQueue
class HashSet
    class LinkedHashSet
class TreeSet
class ArrayDeque
class EnumSet

class EnumMap
class HashMap
    class LinkedHashMap
class TreeMap
class WeakHashMap


List <|.. LinkedList
List <|.. ArrayList
List <|.. Vector
Vector <|-- Stack

Queue <|.. PriorityQueue
Deque <|.. LinkedList

Set <|.. EnumSet
Set <|.. HashSet
HashSet <|-- LinkedHashSet
NavigableSet <|.. TreeSet

Deque <|.. ArrayDeque


Map <|.. EnumMap
Map <|.. HashMap
HashMap <|-- LinkedHashMap
NavigableMap <|.. TreeMap
Map <|.. WeakHashMap


' java.util.concurrent package

' interface hierarchy tree

interface BlockingQueue
    interface BlockingDeque
    interface TransferQueue

interface ConcurrentMap
    interface ConcurrentNavigableMap

Queue <|-- BlockingQueue
BlockingQueue <|-- BlockingDeque
Deque <|-- BlockingDeque

BlockingQueue <|-- TransferQueue

Map <|-- ConcurrentMap
ConcurrentMap <|-- ConcurrentNavigableMap
NavigableMap <|-- ConcurrentNavigableMap

' impl class

class ArrayBlockingQueue
class ConcurrentLinkedQueue
class DelayQueue
class LinkedBlockingDeque
class LinkedBlockingQueue
class LinkedTransferQueue
class PriorityBlockingQueue
class SynchronousQueue

class ConcurrentSkipListSet
class CopyOnWriteArraySet

class CopyOnWriteArrayList

class ConcurrentLinkedDeque

class ConcurrentHashMap
class ConcurrentSkipListMap

BlockingQueue <|.. ArrayBlockingQueue
Queue <|.. ConcurrentLinkedQueue
BlockingQueue <|.. DelayQueue
BlockingDeque <|.. LinkedBlockingDeque
BlockingQueue <|.. LinkedBlockingQueue
TransferQueue <|.. LinkedTransferQueue
BlockingQueue <|.. PriorityBlockingQueue
BlockingQueue <|.. SynchronousQueue

NavigableSet <|.. ConcurrentSkipListSet
Set <|.. CopyOnWriteArraySet

Deque <|.. ConcurrentLinkedDeque


ConcurrentMap <|-- ConcurrentHashMap
ConcurrentNavigableMap <|.. ConcurrentSkipListMap

List <|.. CopyOnWriteArrayList

@enduml
